/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.danielecampogiani

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun testApp() {
        val classUnderTest = App()
        val input = HandlerInput().apply { message = "input" }
        val expected = HandlerOutput("input")
        val output = classUnderTest.handleRequest(input, null)
        assertEquals(expected, output)
    }
}
