/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.danielecampogiani

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler

class App : RequestHandler<HandlerInput, HandlerOutput> {

    val echo: Echo = EchoImpl()

    override fun handleRequest(input: HandlerInput?, context: Context?): HandlerOutput {
        val inputText = input?.message.orEmpty()
        val outputText = echo.echo(inputText)
        return HandlerOutput(outputText)
    }
}

fun main(args: Array<String>) {
}
